server.port = 80
server.document-root = "/tmp"
server.username = "http"
server.groupname = "http"
server.modules = ("mod_proxy","mod_access")

proxy.server = ("/" => (("host" => "proxy_backend", "port" => 8000)))

proxy.header = (
    "upgrade" => "enable",
    "connect" => "enable",
    "force-http10" => "enable"
)

url.access-deny = ( "debug" )